# Generated by Django 3.2.4 on 2021-07-14 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_message_send_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message_send',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.profile'),
        ),
    ]
