# Generated by Django 3.2.4 on 2021-07-15 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='messages',
        ),
    ]
