# Generated by Django 3.2.4 on 2021-07-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profile_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_send',
            new_name='Message_sends',
        ),
    ]
