# Generated by Django 3.2.4 on 2021-07-15 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_message_send_message_sends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_sends',
            new_name='Message',
        ),
    ]
