# Generated by Django 3.2.5 on 2021-07-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_message_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='img',
        ),
    ]
