# Generated by Django 3.2.5 on 2021-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hello ,iam member in secret-space', max_length=100),
        ),
    ]
